name: el_madradja_assaadia
description: برنامج المدرجة السعدية الى فقه الشريعة

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_downloader: ^1.10.4
  path_provider: ^2.0.15
  audioplayers: ^4.1.0
  shared_preferences: ^2.1.1
  scrollable_positioned_list: ^0.3.8
  screen_brightness: ^0.2.2
  flutter_riverpod: ^2.3.6
  intl: ^0.18.0

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - images/
    - data/
  
  fonts:
    - family: Lateef
      fonts:
        - asset: fonts/Lateef-Regular.ttf
        
    - family: Amiri
      fonts:
        - asset: fonts/Amiri-Regular.ttf
    
    - family: ScheherazadeNew
      fonts:
        - asset: fonts/ScheherazadeNew-Regular.ttf
        - asset: fonts/ScheherazadeNew-Bold.ttf
          weight: 700
  